#!/usr/bin/env python3
#
#  ccs2ada
#  Copyright 2023 Jeremy Grosser <jeremy@synack.me>
#  SPDX-License-Identifier: BSD-3-Clause
#
#  The directory called "targetdb" containing device definitions comes from TI
#  Code Composer Studio. On my machine, it's located at:
#
#  ~/ti/ccs1230/ccs/ccs_base/common/targetdb
#
#  It might be in a different location depending on your installation.
#
import xml.etree.ElementTree as ET
import subprocess
import datetime
import argparse
import os.path
import os

import jinja2

# Reserved words in Ada 2022. Any register names that conflict with these are
# suffixed with '_k'
RESERVED = {
    'abort', 'abs', 'abstract', 'accept', 'access', 'aliased', 'all', 'and',
    'array', 'at', 'begin', 'body', 'case', 'constant', 'declare', 'delay',
    'delta', 'digits', 'do', 'else', 'elsif', 'end', 'entry', 'exception',
    'exit', 'for', 'function', 'generic', 'goto', 'if', 'in', 'interface',
    'is', 'limited', 'loop', 'mod', 'new', 'not', 'null', 'of', 'or', 'others',
    'out', 'overriding', 'package', 'parallel', 'pragma', 'private',
    'procedure', 'protected', 'raise', 'range', 'record', 'rem', 'renames',
    'requeue', 'return', 'reverse', 'select', 'separate', 'some', 'subtype',
    'synchronized', 'tagged', 'task', 'terminate', 'then', 'type', 'until',
    'use', 'when', 'while', 'with', 'xor'
}

env = jinja2.Environment(loader=jinja2.FileSystemLoader(os.path.join(os.path.dirname(__file__), 'templates')))


def hex2int(x):
    if isinstance(x, str) and x.startswith('0x'):
        return int(x[2:], 16)
    else:
        return x


def hexformat(x):
    return '16#%X#' % x


def rename(name):
    if name.lower() in RESERVED:
        return name + '_k'
    else:
        return name


env.filters['rename'] = rename
env.filters['hexformat'] = hexformat

try:
    env.globals['git_revision'] = subprocess.run(('git', 'rev-parse', '--short', 'HEAD'), capture_output=True).stdout.decode('utf8').strip('\r\n\t ')
except:
    env.globals['git_revision'] = 'unknown'

now = datetime.datetime.utcnow()
env.globals['timestamp'] = now.isoformat()


def walk_registers(parent_node, module, base_offset=None):
    if base_offset is None:
        base_offset = 0

    registers = []
    offset = 0

    for register_node in parent_node.findall('register'):
        register = {
            'id': register_node.attrib['id'].strip('_'),
            'size': int(register_node.attrib['width']),
            'instances': int(register_node.attrib.get('instances', 1)),
            'description': register_node.attrib.get('description', ''),
            'bitfields': [],
        }

        if register['id'].startswith(module['id'] + '_'):
            register['id'] = register['id'].split('_', 1)[1]

        if 'offset' in register_node.attrib:
            offset = int(register_node.attrib['offset'], 16)
            register['offset'] = base_offset + hex2int(offset)
        else:
            offset += int(register['size'] / 8)
            register['offset'] = base_offset + hex2int(offset)

        #if register['offset'] > (module['size'] / 8):
        #    print('WARNING: Register %s.%s offset is outside of module address space.' % 
        #        (module['id'], register['id']))

        for bitfield_node in register_node.iter('bitfield'):
            bitfield = {
                'id': bitfield_node.attrib['id'].strip('_'),
                'description': bitfield_node.attrib['description'],
                'size': int(bitfield_node.attrib['width']),
                'resetval': hex2int(bitfield_node.attrib.get('resetval', '0x0')),
                'first': int(bitfield_node.attrib['end']),
                'last': int(bitfield_node.attrib['begin']),
            }
            register['bitfields'].append(bitfield)

        register['size'] = register['size'] * register['instances']

        registers.append(register)
    return registers


def parse_file(outdir, device_path):
    device_path = os.path.normpath(device_path)
    device_tree = ET.parse(device_path)
    device_node = device_tree.getroot()
    device = {
        'id': device_node.attrib['id'],
        'path': device_path,
        'modules': {}
    }

    for cpu_node in device_node.iter('cpu'):
        for instance_node in cpu_node.iter('instance'):
            module_path = os.path.join(os.path.dirname(device_path), instance_node.attrib['href'])
            module_path = os.path.normpath(module_path)
            module_tree = ET.parse(module_path)
            module_node = module_tree.getroot()
            module = {
                'id': module_node.attrib.get('id') or module_node.attrib.get('name'),
                'path': module_path,
                'registers': [],
                'instances': [{
                    'baseaddr': hex2int(instance_node.attrib['baseaddr']),
                }],
            }
            if not module['id']:
                raise Exception('No id for module at', module_path)

            if module['id'] in device['modules']:
                existing = device['modules'][module['id']]
                if existing['path'] != module['path']:
                    print('WARNING: Multiple definitions of', module['id'], ':')
                    print(existing['path'])
                    print(module['path'])
                existing['instances'].append(module['instances'][0])
                continue

            offset = 0

            module['registers'] = walk_registers(module_node, module)

            for group_node in module_node.findall('group'):
                module['registers'] += walk_registers(group_node, module, base_offset=hex2int(group_node.attrib['offset']))

            module['registers'].sort(key=lambda x: x['offset'])

            if len(module['registers']) == 0:
                print('WARNING: Module %s has no registers!' % module['id'])
            else:
                last_register = module['registers'][-1]
                module['size'] = (last_register['offset'] * 8) + (last_register['size'] * last_register['instances'])
                device['modules'][module['id']] = module

    device_template = env.get_template('device.ads')
    path = os.path.join(outdir, '%s.ads' % device['id'])
    path = path.lower()
    with open(path, 'w') as fd:
        fd.write(device_template.render(device=device))

    module_template = env.get_template('module.ads')
    for module in device['modules'].values():
        path = os.path.join(outdir, '%s-%s.ads' % (device['id'], module['id']))
        path = path.lower()
        print(path)
        with open(path, 'w') as fd:
            fd.write(module_template.render(device=device, module=module))


if __name__ == '__main__':
    p = argparse.ArgumentParser(
        prog='ccs2ada',
        description='Translates Texas Instruments Code Composer Studio device definitions to Ada package specifications',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument('--targetdb',
        default='~/ti/ccs1230/ccs/ccs_base/common/targetdb',
        help='Path to targetdb, usually under ccs_base')
    p.add_argument('--output',
        default='./gen',
        help='Path to output directory')
    p.add_argument('device',
        default='rm42l432',
        help='Device to generate specs for. See targetdb/devices/')
    args = p.parse_args()

    if not os.path.exists(args.output):
        os.makedirs(args.output)

    device_file = os.path.join(os.path.expanduser(args.targetdb), 'devices', args.device + '.xml')
    parse_file(args.output, device_file)
