{% block preamble -%}
pragma Style_Checks (Off);
pragma Restrictions (No_Elaboration_Code);

--  Generated by ccs2ada ({{ git_revision }}) at {{ timestamp }}
{% endblock -%}
{% block package_spec %}{% endblock -%}
